version: '3.1'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:aa
      - MYSQL_DATABASE:roche
      - MYSQL_USER:user
      - MYSQL_PASSWORD:password
    
  #adminer:
   # image: adminer
    #restart: always
    #ports:
    #  - "8080:8080" 
    